### ISSUE TITLE
Linux install → Ubuntu install

### ISSUE THREAD

**Issue by Airon90** [Tuxemon/Tuxemon-Website#3]
[These](https://tuxemon.org/linux-install.html) are Ubuntu installation instruction only.

I suggest to rename the page to "Ubuntu install" and make "Linux install" a list of subpages for each Linux distributions (Ubuntu and Fedora by now. Arch Linux on the way: see #2)

**Comment by ShadowApex** [comment]
Thanks for this suggestion! I made this change in commit cfcd01f92d369cbb2e4e28b979db6cb7726c0462
